# Generated by Django 5.0.6 on 2024-05-31 15:35

import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the full name. * (Required)', max_length=255)),
                ('short_name', models.CharField(help_text='Enter the short name. * (Required)', max_length=255)),
                ('description', models.TextField(help_text='Enter the description. * (Required)')),
                ('primary_email', models.EmailField(help_text='Enter the primary contact email. * (Required)', max_length=254)),
                ('secondary_email', models.EmailField(help_text='Enter the secondary contact email. * (Required)', max_length=254)),
                ('primary_phone', models.CharField(help_text='Enter the primary contact phone number. * (Required)', max_length=255)),
                ('secondary_phone', models.CharField(help_text='Enter the secondary contact phone number. * (Required)', max_length=255)),
                ('building', models.CharField(blank=True, help_text='Enter the location building', max_length=255)),
                ('street', models.CharField(blank=True, help_text='Enter the location street', max_length=255)),
                ('PO_box', models.CharField(blank=True, help_text='Enter the P.O Box', max_length=255)),
                ('city_name', models.CharField(blank=True, help_text='Enter the city name', max_length=255)),
                ('zip_code', models.CharField(blank=True, help_text='Enter the zip code', max_length=255)),
                ('open_days', models.CharField(blank=True, help_text='e.g Monday - Friday', max_length=255)),
                ('open_hours', models.CharField(blank=True, help_text='e.g 8:15AM - 05:00PM', max_length=255)),
                ('facebook', models.URLField(blank=True, help_text='Enter the facebook account url', max_length=255)),
                ('twitter_x', models.URLField(blank=True, help_text='Enter the X account url', max_length=255)),
                ('instagram', models.URLField(blank=True, help_text='Enter the Instagram account url', max_length=255)),
                ('linkedin', models.URLField(blank=True, help_text='Enter the Linkedin account url', max_length=255)),
                ('whatsapp', models.URLField(blank=True, help_text="Enter the Whatsapp url in the format 'https://wa.me/254700000000'. Replace with appropriate phone number", max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Base Information',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('role', models.CharField(blank=True, choices=[('USER', 'User')], max_length=50)),
                ('image', models.ImageField(blank=True, default='defaults/default_profile.jpg', help_text='Upload an image that is 600x600', upload_to='students/')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
