# Generated by Django 5.0.6 on 2024-06-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='root',
            name='secondary_email',
            field=models.EmailField(blank=True, help_text='Enter the secondary contact email.', max_length=254),
        ),
    ]
