# Generated by Django 5.0.6 on 2024-06-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the full name. * (Required)', max_length=255)),
                ('short_name', models.CharField(blank=True, help_text='Enter the short name.', max_length=255)),
                ('motto', models.CharField(blank=True, help_text='Enter the motto.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Enter the description.')),
                ('logo', models.ImageField(blank=True, help_text='Pick a logo preferably of size 500x500', null=True, upload_to='base/')),
                ('website', models.URLField(blank=True, help_text='Enter the website url', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Base Information',
                'db_table': 'api_base',
            },
        ),
    ]
