# Generated by Django 5.0.6 on 2024-06-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Pick a logo preferably of size 500x500', null=True, upload_to='base/')),
                ('name', models.CharField(blank=True, help_text='Enter the full name.', max_length=255)),
                ('short_name', models.CharField(blank=True, help_text='Enter the short name.', max_length=255)),
                ('motto', models.CharField(blank=True, help_text='Enter the motto.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Enter the description.')),
                ('website', models.URLField(blank=True, help_text='Enter the website url', max_length=255)),
                ('primary_phone', models.CharField(blank=True, help_text='Enter the primary contact phone number.', max_length=255)),
                ('secondary_phone', models.CharField(blank=True, help_text='Enter the secondary contact phone number.', max_length=255)),
                ('primary_email', models.EmailField(blank=True, help_text='Enter the primary contact email.', max_length=254)),
                ('secondary_email', models.EmailField(blank=True, help_text='Enter the secondary contact email.', max_length=254)),
                ('building', models.CharField(blank=True, help_text='Enter the location building', max_length=255)),
                ('street', models.CharField(blank=True, help_text='Enter the location street', max_length=255)),
                ('PO_box', models.CharField(blank=True, help_text='Enter the P.O Box', max_length=255)),
                ('city_name', models.CharField(blank=True, help_text='Enter the city name', max_length=255)),
                ('zip_code', models.CharField(blank=True, help_text='Enter the zip code', max_length=255)),
                ('open_days', models.CharField(blank=True, help_text='e.g Monday - Friday', max_length=255)),
                ('open_hours', models.CharField(blank=True, help_text='e.g 8:15AM - 05:00PM', max_length=255)),
                ('facebook', models.URLField(blank=True, help_text='Enter the facebook account url', max_length=255)),
                ('twitter_x', models.URLField(blank=True, help_text='Enter the X account url', max_length=255)),
                ('instagram', models.URLField(blank=True, help_text='Enter the Instagram account url', max_length=255)),
                ('linkedin', models.URLField(blank=True, help_text='Enter the Linkedin account url', max_length=255)),
                ('whatsapp', models.URLField(blank=True, help_text="Enter the Whatsapp url in the format 'https://wa.me/254700000000'. Replace with appropriate phone number", max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Base Information',
                'db_table': 'app_base',
            },
        ),
    ]
