# Generated by Django 5.1 on 2024-08-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Facebook URL', null=True)),
                ('twitter_x', models.URLField(blank=True, help_text='Twitter X URL', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Instagram URL', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn URL', null=True)),
                ('whatsapp', models.URLField(blank=True, help_text='WhatsApp URL', null=True)),
            ],
            options={
                'verbose_name_plural': 'Social Links',
                'db_table': 'components_sociallinks',
            },
        ),
    ]
