import type { Metadata } from "next";
import 'bootstrap-icons/font/bootstrap-icons.css';
import "./globals.scss";

export const metadata: Metadata = {
  title: "Lox Website Template",
  description: "Generated by create next app",
  metadataBase: new URL('https://lox-website-template.duckdns.org'),
};


export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
