# Generated by Django 5.1.4 on 2025-01-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_phone', models.CharField(help_text='Main contact number including country code (e.g., +1 234 567 8900)', max_length=255)),
                ('secondary_phone', models.CharField(blank=True, help_text='(Optional) Enter the secondary phone number.', max_length=255)),
                ('primary_email', models.EmailField(help_text='Main contact email address for business inquiries', max_length=255)),
                ('secondary_email', models.EmailField(blank=True, help_text='(Optional) Enter the secondary email address.', max_length=255)),
                ('city_name', models.CharField(help_text='City where your business is located', max_length=255)),
                ('PO_box', models.CharField(blank=True, help_text='(Optional) Enter the P.O. Box.', max_length=255)),
                ('street', models.CharField(blank=True, help_text='(Optional) Enter the street address.', max_length=255)),
                ('open_days', models.TextField(help_text="Business operating days (e.g., 'Monday to Friday' or 'Monday - Saturday')")),
                ('open_hours', models.TextField(help_text="Business operating hours in your local timezone (e.g., '9:00 AM - 6:00 PM EAT')")),
                ('map', models.URLField(blank=True, help_text="Google Maps embed URL (obtain this from Google Maps by clicking 'Share' and selecting 'Embed a map')", max_length=500, null=True)),
                ('social_media_links_version', models.CharField(choices=[('V1', 'Version 1'), ('V2', 'Version 2'), ('V3', 'Version 3')], default='V1', help_text='Select the version for the Social Media Links section.', max_length=2)),
                ('facebook', models.URLField(blank=True, help_text='(Optional) Enter the Facebook URL.')),
                ('instagram', models.URLField(blank=True, help_text='(Optional) Enter the Instagram URL.')),
                ('twitter_x', models.URLField(blank=True, help_text='(Optional) Enter the X (formerly Twitter) URL.')),
                ('linkedin', models.URLField(blank=True, help_text='(Optional) Enter the LinkedIn URL.')),
                ('spotify', models.URLField(blank=True, help_text='(Optional) Enter the Spotify URL.')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text='The complete name of your application as it should appear in official contexts', max_length=255)),
                ('short_name', models.CharField(blank=True, help_text='A shorter version of your app name, suitable for headers and mobile displays', max_length=50)),
                ('motto', models.TextField(blank=True, help_text="A brief tagline or slogan that captures your app's mission or value proposition")),
                ('website', models.URLField(blank=True, help_text='The primary website URL for your application (include https://)')),
                ('theme_color', models.CharField(choices=[('#e84545', 'red')], default='#e84545', help_text='Select the primary theme color for your application from the available options', max_length=7)),
                ('background_color', models.CharField(blank=True, default='#ffffff', help_text='Background color for the application (hex format, e.g. #ffffff)', max_length=7)),
                ('colored_logo_full_image', models.ImageField(blank=True, help_text='Full-color version of your main logo (500x500px recommended) for use on light backgrounds', null=True, upload_to='metadata/')),
                ('colored_logo_mini_image', models.ImageField(blank=True, help_text='Compact version of your colored logo (500x500px recommended) for mobile and small displays', null=True, upload_to='metadata/')),
                ('light_logo_full_image', models.ImageField(blank=True, help_text='Light-colored version of your main logo (500x500px recommended) for use on dark backgrounds', null=True, upload_to='metadata/')),
                ('light_logo_mini_image', models.ImageField(blank=True, help_text='Compact light-colored version of your logo (500x500px recommended) for mobile and small displays on dark backgrounds', null=True, upload_to='metadata/')),
                ('dark_logo_full_image', models.ImageField(blank=True, help_text='Dark-colored version of your main logo (500x500px recommended) for use on light backgrounds', null=True, upload_to='metadata/')),
                ('dark_logo_mini_image', models.ImageField(blank=True, help_text='Compact dark-colored version of your logo (500x500px recommended) for mobile and small displays on light backgrounds', null=True, upload_to='metadata/')),
                ('favicon', models.ImageField(blank=True, help_text='Browser tab icon (32x32px, .ico format recommended). This appears in browser tabs and bookmarks', null=True, upload_to='metadata/')),
                ('apple_touch_icon', models.ImageField(blank=True, help_text='iOS home screen icon (180x180px, .png format). This appears when users add your site to their home screen', null=True, upload_to='metadata/')),
                ('pwa_192', models.ImageField(blank=True, help_text='PWA icon (192x192px, .png format). Required for Progressive Web Apps', null=True, upload_to='metadata/')),
                ('pwa_512', models.ImageField(blank=True, help_text='PWA icon (512x512px, .png format). Required for Progressive Web Apps', null=True, upload_to='metadata/')),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image (1200x630px recommended). This appears when sharing on social media', null=True, upload_to='metadata/')),
                ('twitter_image', models.ImageField(blank=True, help_text='Twitter Card image (1200x600px recommended). This appears when sharing on Twitter', null=True, upload_to='metadata/')),
            ],
            options={
                'verbose_name': 'App Metadata',
                'verbose_name_plural': 'App Metadata',
            },
        ),
    ]
