# Generated by Django 5.1 on 2024-08-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, help_text='Website', null=True)),
                ('primary_phone', models.CharField(help_text='Primary Phone Number', max_length=255)),
                ('secondary_phone', models.CharField(blank=True, help_text='Secondary Phone Number', max_length=255)),
                ('primary_email', models.EmailField(help_text='Primary Email', max_length=255)),
                ('secondary_email', models.EmailField(blank=True, help_text='Secondary Email', max_length=255)),
                ('city_name', models.CharField(help_text='City Name', max_length=255)),
                ('PO_box', models.CharField(blank=True, help_text='P.O Box', max_length=255)),
                ('street', models.CharField(blank=True, help_text='Street', max_length=255)),
                ('open_hours', models.TextField(help_text='e.g Monday to Friday 8:00am - 5:00pm')),
                ('map', models.URLField(blank=True, help_text='Get the embedded iframe url from Google Maps', max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Information',
                'db_table': 'components_contact',
            },
        ),
    ]
