"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 5.0.6.
For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from datetime import timedelta
from decouple import config
from pathlib import Path

# from .urls import static_url, media_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# Environment

ENVIRONMENT = config("NEXT_PUBLIC_ENVIRONMENT", default="production")

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = False if ENVIRONMENT == "production" else True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "loxinformatics",
    "143.244.178.221",
    "loxinformatics.com",
    "www.loxinformatics.com",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third-party
    "rest_framework",
    "django_filters",
    "corsheaders",
    "rest_framework_simplejwt.token_blacklist",
    # required
    "base",
    # optional
    "authentication",
    "accounts",
    "contact",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # cors headers middleware
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

ROOT_URL = "api"  # leave out the forward slash

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": "localhost",
        "PORT": "5432",
        "USER": "lox",
        "NAME": "loxdb",
        "PASSWORD": SECRET_KEY,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Nairobi"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
# Ensure your NGINX block path start with the ROOT URL then STATIC_URL
# e.g location /ROOT_URL/STATIC_URL
# Ensure root or alias string location in NGINX ends with 'core'
# e.g. alias /path/to/project/core;

STATIC_URL = ROOT_URL + "/static/"

STATIC_ROOT = BASE_DIR / "core" / STATIC_URL


# Media files
# https://docs.djangoproject.com/en/4.2/ref/settings/#media-files
# Ensure your NGINX block path start with the ROOT URL then MEDIA_URL
# e.g location /ROOT_URL/MEDIA_URL
# Ensure root or alias string location in NGINX ends with 'core'
# e.g. alias /path/to/project/core;

MEDIA_URL = ROOT_URL + "/media/"

MEDIA_ROOT = BASE_DIR / "core" / MEDIA_URL


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Email
# https://docs.djangoproject.com/en/4.2/topics/email/

EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
    if ENVIRONMENT == "production"
    else "django.core.mail.backends.console.EmailBackend"
)

EMAIL_HOST = "smtp.ionos.com"

EMAIL_PORT = "587"

EMAIL_USE_TLS = True

EMAIL_USE_SSL = False

EMAIL_HOST_USER = "website@loxinformatics.com"

EMAIL_HOST_PASSWORD = SECRET_KEY


# Authentication
# https://docs.djangoproject.com/en/stable/topics/auth/

AUTH_USER_MODEL = "accounts.Account"

AUTHENTICATION_BACKENDS = [
    # "accounts.backends.UsernameOrEmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]


# Django Rest Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    # "PAGE_SIZE": 10,
}


# corsheaders
# https://pypi.org/project/django-cors-headers/
# Remember to add "corsheaders.middleware.CorsMiddleware" to MIDDLEWARE

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:3000",
    "http://localhost:3000",
    "https://loxinformatics.com",
    "https://www.loxinformatics.com",
]


# Djangorestframework-simplejwt
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html#

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    # custom
    "AUTH_COOKIE": "access_token",
    "TOKEN_OBTAIN_SERIALIZER": "authentication.serializers.TokenSerializer",
}
