name: executing remote ssh commands
on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  build:
    name: Pull changes
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}  # Your server's IP address
          username: ${{ secrets.SERVER_USERNAME }}  # Your SSH username
          password: ${{ secrets.SERVER_PASSWORD }}  # Your SSH password
          port: ${{ secrets.SERVER_SSH_PORT }}  # SSH port (default is 22)
          script: |
            cd /repos/website-template/
            git pull origin main  # Change 'main' to your branch name
            npm install
            npm run build
            pipenv install
            pipenv run python manage.py makemigrations
            pipenv run python manage.py migrate
            pipenv run python manage.py collectstatic --no-input
            rm .env
            touch .env
            echo "ENVIRONMENT=${{ vars.ENVIRONMENT }}" >> .env
            echo "DJANGO_SECRET_KEY=${{ vars.DJANGO_SECRET_KEY }}" >> .env
            echo "ALLOWED_HOSTS=${{ vars.ALLOWED_HOSTS }}" >> .env
            echo "DB_ENGINE=${{ vars.DB_ENGINE }}" >> .env
            echo "DB_NAME=${{ vars.DB_NAME }}" >> .env
            echo "DB_USER=${{ vars.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_HOST=${{ vars.DB_HOST }}" >> .env
            echo "DB_PORT=${{ vars.DB_PORT }}" >> .env
            echo "EMAIL_HOST=${{ vars.EMAIL_HOST }}" >> .env
            echo "EMAIL_PORT=${{ vars.EMAIL_PORT }}" >> .env
            echo "EMAIL_USE_TLS=${{ vars.EMAIL_USE_TLS }}" >> .env
            echo "EMAIL_USE_SSL=${{ vars.EMAIL_USE_SSL }}" >> .env
            echo "EMAIL_HOST_USER=${{ vars.EMAIL_HOST_USER }}" >> .env
            echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> .env
            echo ${{ secrets.SERVER_PASSWORD }} | sudo -S service gunicorn-website-template restart
            echo ${{ secrets.SERVER_PASSWORD }} | sudo -S service nginx restart